name: Comment on pull request
description: Create and update comment on pull request by key comment in body
inputs:
  key:
    description: Unique key for finding comment to update
    required: true
  body:
    description: Comment body (key will be appendend as comment)
    required: true

runs:
  using: composite
  steps:
    - id: comment-body-includes
      uses: actions/github-script@v6
      name: "Comment id (key: ${{ inputs.key }})"
      with:
        script: |
          const key = ${{ toJSON(inputs.key) }};

          core.setOutput('comment', `<!-- key: ${key} -->`)

    - name: Find comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: "github-actions[bot]"
        body-includes: ${{ steps.comment-body-includes.outputs.comment }}

    - name: Create or update comment
      uses: peter-evans/create-or-update-comment@v3
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        edit-mode: replace
        body: "${{ inputs.body }}"
