name: Run knip

on:
  pull_request:

jobs:
  knip:
    name: "knip${{ matrix.args }}"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    strategy:
      matrix:
        args: ["", " --workspace apps/next-site"]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: jdx/rtx-action@v1

      - run: bun install

      - name: Versions
        id: versions
        uses: actions/github-script@v6
        with:
          script: |
            function e(cmd) {
              return require('child_process').execSync(cmd).toString().trim();
            }

            core.setOutput('node-version', e("node --version"))
            core.setOutput('bun-version', e("bun --version"))
            core.setOutput('knip-version', e("./node_modules/.bin/knip --version"))

      - id: knip
        name: Run knip ${{ matrix.args }}
        run: |
          echo "output<<'KNIP_OUTPUT'" >> "$GITHUB_OUTPUT"
          (./node_modules/.bin/knip${{ matrix.args }} || true) 2>err | tee -a "$GITHUB_OUTPUT"
          echo "'KNIP_OUTPUT'" >> "$GITHUB_OUTPUT"

          echo "error<<'KNIP_ERROR'" >> "$GITHUB_OUTPUT"
          cat err | tee -a "$GITHUB_OUTPUT"
          echo "'KNIP_ERROR'" >> "$GITHUB_OUTPUT"

          echo '"'$(cat "$GITHUB_OUTPUT")'"'

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: Knip${{ matrix.args }} output

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            ## Versions

            - `node@${{ steps.versions.outputs.node-version }}`
            - `bun@${{ steps.versions.outputs.bun-version }}`
            - `knip@${{ steps.versions.outputs.knip-version }}`


            ## Knip${{ matrix.args }} output

            ```
            ${{ steps.knip.outputs.output }}
            ```

            ### Knip error output

            ```
            ${{ steps.knip.outputs.error }}
            ```
