name: Run knip

on:
  pull_request:

jobs:
  knip:
    name: "knip${{ matrix.args }}"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    strategy:
      matrix:
        args: ["", " --workspace apps/next-site"]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: jdx/rtx-action@v1

      - run: bun install

      - id: knip
        name: Run knip ${{ matrix.args }}
        run: |
          echo "output<<'KNIP_OUTPUT'" >> "$GITHUB_OUTPUT"
          (./node_modules/.bin/knip${{ matrix.args }} || true) 2>err | tee -a "$GITHUB_OUTPUT"
          echo "'KNIP_OUTPUT'" >> "$GITHUB_OUTPUT"

          echo "error<<'KNIP_ERROR'" >> "$GITHUB_OUTPUT"
          cat err | tee -a "$GITHUB_OUTPUT"
          echo "'KNIP_ERROR'" >> "$GITHUB_OUTPUT"

          echo '"'$(cat "$GITHUB_OUTPUT")'"'

      - name: Create or update comment
        uses: ./.github/actions/comment
        with:
          key: knip${{ matrix.args }}
          body: |
            ## Knip${{ matrix.args }} output

            ```
            ${{ steps.knip.outputs.output }}
            ```

            ### Knip error output

            ```
            ${{ steps.knip.outputs.error }}
            ```
