name: Run knip

on:
  pull_request:

jobs:
  knip:
    name: "knip${{ matrix.args }}"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    strategy:
      matrix:
        args: ["", " --workspace apps/next-site"]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install

      - id: knip
        name: Run knip ${{ matrix.args }}
        run: |
          echo "version<<'KNIP_VERSION'" >> "$GITHUB_OUTPUT"
          (./node_modules/.bin/knip --version || true) 2>err | tee -a "$GITHUB_OUTPUT"
          echo "'KNIP_VERSION'" >> "$GITHUB_OUTPUT"

          echo "output<<'KNIP_OUTPUT'" >> "$GITHUB_OUTPUT"
          (./node_modules/.bin/knip${{ matrix.args }} || true) 2>err | tee -a "$GITHUB_OUTPUT"
          echo "'KNIP_OUTPUT'" >> "$GITHUB_OUTPUT"

          echo "error<<'KNIP_ERROR'" >> "$GITHUB_OUTPUT"
          cat err | tee -a "$GITHUB_OUTPUT"
          echo "'KNIP_ERROR'" >> "$GITHUB_OUTPUT"

          echo '"'$(cat "$GITHUB_OUTPUT")'"'

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: Knip${{ matrix.args }} output

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            ## Knip version

            ```
            ${{ steps.knip.outputs.version }}
            ```

            ## Knip${{ matrix.args }} output

            ```
            ${{ steps.knip.outputs.output }}
            ```

            ### Knip error output

            ```
            ${{ steps.knip.outputs.error }}
            ```
